import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import getUsers from '../services/getUsers'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [candidatesResults, setCandidatesResults] = useState([{}]);

  useEffect(()=>{
    getUsers("inputValueToSearchUserRepos.input").then(data =>{
      setCandidatesResults(data.data);
    })
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Repos Git Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">GitHub Rest/API Repos!</a>
        </h1>
        <div className={styles.containerList}>
          <ul className={styles.List}>
          {
            candidatesResults.map(candidate => {
              return (
                <>
                <fieldset className={styles.optionList}>
                <img src={candidate.avatar_url} alt="Vercel Logo" width={36} height={36} />
                  <Link href="https://github.com/" as={`https://github.com/${candidate.login}`}>
                    <a target="_blank"> 
                      {candidate.login} 
                    </a>
                  </Link>
                </fieldset>
                <br></br>
                </>
              )
            })
          }
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
